% Perfil: Aluno voltado para Ciencia de Dados
resposta(1, n).
resposta(2, n).
resposta(3, n).
resposta(4, n).
resposta(5, n).
resposta(6, s).
resposta(7, s).
resposta(8, s).
resposta(9, s).
resposta(10, n).
resposta(11, n).
resposta(12, n).
resposta(13, n).
resposta(14, n).
resposta(15, n).
resposta(16, n).
resposta(17, n).
resposta(18, n).
resposta(19, n).
resposta(20, n).
resposta(21, n).
resposta(22, n).
resposta(23, n).
resposta(24, n).
resposta(25, n).