% Perfil: Aluno voltado para Redes e Infraestrutura
resposta(1, n).
resposta(2, n).
resposta(3, n).
resposta(4, n).
resposta(5, n).
resposta(6, n).
resposta(7, n).
resposta(8, n).
resposta(9, n).
resposta(10, n).
resposta(11, n).
resposta(12, n).
resposta(13, n).
resposta(14, n).
resposta(15, n).
resposta(16, n).
resposta(17, n).
resposta(18, n).
resposta(19, n).
resposta(20, n).
resposta(21, n).
resposta(22, s).
resposta(23, s).
resposta(24, s).
resposta(25, n).